/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hwjdev817;

import hwjdev817.service.Client;
import hwjdev817.service.ClientService;
import hwjdev817.storage.Database;
import hwjdev817.storage.DatabaseInitService;
import org.checkerframework.checker.units.qual.C;

import java.sql.SQLException;
import java.util.List;

public class App {


    public static void main(String[] args) throws Exception {
        Database database = Database.getInstance();

        new DatabaseInitService().initDb(database);

        ClientService clientService = new ClientService(database);

        List<Client> clients = clientService.listAll();
        System.out.println(" clients = "+clients.toString());

        try { clientService.create("July");
        }
        catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
        }

        Long id=5l;
        String name = clientService.getById(id);
        System.out.println(" id= "+id+" name = "+name);

        name="Maxim";
        try {clientService.setName(id,name);;
        }
        catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
        }
        System.out.println(" id= "+id+" name = "+name);

        clientService.deleteById(id);
        clients = clientService.listAll();
        System.out.println(" clients = "+clients.toString());


//"Id incorrect value!"
        id=-1l;
        try {clientService.setName(id,name);;
        }
        catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
        }
id=null;
        try {clientService.setName(id,name);;
        }
        catch (NullPointerException e) {
            System.out.println(e.getMessage());
        }
        // Invalid characters in name!
        id=6l;
        name="Max%im";
        try {clientService.setName(id,name);;
        }
        catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
        }
        clients = clientService.listAll();
        System.out.println(" clients = "+clients.toString());


 //Name can not be empty!
        name="";
        try { clientService.create( name);
        }
        catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
        }

//   Invalid characters in name!
        name="Jul&y";
        try {clientService.create(name);
        }
        catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
        }

//    Length name too long!
        StringBuilder result = new StringBuilder();
        for(int i = 0; i < 1000; i++) {
            result.append(i);
        }

        try { clientService.create(result.toString());
        }
        catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
        }




    }
}
